name: gnome-sudoku
adopt-info: gnome-sudoku
summary: Test your logic skills in this number grid puzzle
description: |
  Play the popular Japanese logic game. GNOME Sudoku is a must-install for
  Sudoku lovers, with a simple, unobtrusive interface that makes playing
  Sudoku fun for players of any skill level.

  Each game is assigned a difficulty similar to those given by newspapers
  and websites, so your game will be as easy or as difficult as you want it
  to be.

  If you like to play on paper, you can print games out. You can choose how
  many games you want to print per page and what difficulty of games you
  want to print: as a result, GNOME Sudoku can act a renewable Sudoku book
  for you.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-sudoku:
    interface: dbus
    bus: session
    name: org.gnome.Sudoku

apps:
  gnome-sudoku:
    command: desktop-launch gnome-sudoku
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Sudoku.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  gnome-sudoku:
    after: [desktop-gnome-platform]
    source: https://gitlab.gnome.org/GNOME/gnome-sudoku.git
    source-type: git
    source-branch: gnome-3-36
    plugin: meson
    meson-parameters: [--prefix=/usr]
    organize:
      snap/gnome-sudoku/current/usr: usr
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - appstream-util
      - intltool
      - libgee-0.8-dev
      - libjson-glib-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libqqwing-dev
      - valac
      - yelp-tools
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
      sed -i.bak -e 's|help_media,|help_media, symlink_media: false,|g' help/meson.build

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  libraries:
    plugin: nil
    stage-packages:
      - libqqwing2v5
      - libgee-0.8-2
    prime:
      - "usr/lib/*/libqqwing*"
      - "usr/lib/*/libgee*"
