name: gnome-sudoku
adopt-info: gnome-sudoku
summary: Test your logic skills in this number grid puzzle
description: |
  Play the popular Japanese logic game. GNOME Sudoku is a must-install for
  Sudoku lovers, with a simple, unobtrusive interface that makes playing
  Sudoku fun for players of any skill level.

  Each game is assigned a difficulty similar to those given by newspapers
  and websites, so your game will be as easy or as difficult as you want it
  to be.

  If you like to play on paper, you can print games out. You can choose how
  many games you want to print per page and what difficulty of games you
  want to print: as a result, GNOME Sudoku can act a renewable Sudoku book
  for you.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22


slots:
  # for GtkApplication registration
  gnome-sudoku:
    interface: dbus
    bus: session
    name: org.gnome.Sudoku

apps:
  gnome-sudoku:
    extensions: [ gnome ]
    command: usr/bin/gnome-sudoku
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.Sudoku.desktop

parts:
  gnome-sudoku:
# ext:updatesnap
#   version-format:
#     lower-than: '46'
#     no-9x-revisions: true
    source: https://gitlab.gnome.org/GNOME/gnome-sudoku.git
    source-type: git
    source-tag: '45.1'
    source-depth: 1
    plugin: meson
    parse-info: [usr/share/metainfo/org.gnome.Sudoku.appdata.xml]
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libqqwing-dev
    override-pull: |
      craftctl default
      sed -i.bak -e 's|help_media,|help_media, symlink_media: false,|g' help/meson.build

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  libraries:
    plugin: nil
    stage-packages:
      - libqqwing2v5
    prime:
      - "usr/lib/*/libqqwing*"
